### ISSUE TITLE
How to do group Hungary matching？

### ISSUE THREAD

**Issue by notfacezhi** [horrible-dong/TeamDETR#3]
Hi~ I have a question, grouping for Hungarian matching, the premise is that the group to be matched with Hungary must have a GT obj corresponding to it, so what should be done with the group of queries that do not have GT obj corresponding to it? Is it directly discarded? Do neither negative samples nor positive samples? Or only negative samples?

**Comment by horrible-dong** [comment]
There does exist such a case where a group of queries (a scale range) corresponds to no GTs, and this group's cost matrix is empty, then the Hungarian Matching result is empty too. The empty Hungarian Matching result indicates all queries in this group are negative samples since they have failed to match any GTs, so there is no bbox_loss, but there still be cls_loss where this group of queries should be classified into background.

**Comment by notfacezhi** [comment]
The scale [0, 0.2, 0.4, 1] mentioned in the paper is that different scales GT obj are divided into one of the groups, so is the number of queries corresponding to each group or the query division ratio also the above? Or is it a fixed ratio? Or does it change adaptively with model training?

**Comment by horrible-dong** [comment]
In the paper, the query numbers are fixed to 65, 20, 15 corresponding to the scales (0, 0.2], (0.2, 0.4], (0.4, 1].

**Comment by notfacezhi** [comment]
Thanks for the reply.

**Comment by notfacezhi** [comment]
Is the initial wh of each query random?

**Comment by horrible-dong** [comment]
No. The w and h of queries in the k-th group are uniformly initialized to $$(s_k^{min} + s_k^{max}) / 2$$
